version: '3.8'
services:
  test-app:
    image: nginx:alpine
    container_name: test-app
    restart: unless-stopped
    networks:
      - traefik_net  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-app.rule=Host(`test-app.staging.dicoded.vegarislabs.com`)"
      - "traefik.http.routers.test-app.entrypoints=websecure"
      - "traefik.http.routers.test-app.tls.certresolver=leresolver"
      - "traefik.http.services.test-app.loadbalancer.server.port=80"

networks:
  traefik_net:
    external: true
